### PR TITLE
Accept whitespace before braces in @Component

### PR DESCRIPTION
**Pull request by db6edr**
Change componentRegex to also accept a single whitespace before { and after }. This supports further coding styles

### CODE REVIEW

**Review by cebor — CHANGES_REQUESTED** [review]
Nice, can you please remove the version update in `package.json`, i will bump it in a separate commit.

Thanks!

**Review by cebor — APPROVED** [review]

**Comment by cebor** [comment]
Thanks for the PR.

But have you any source for the new coding styles for me?

Never seen this before ...

```
@Component( {
  selector: 'admin-users'
} )
```

**Comment by db6edr** [comment]
Sure: https://github.com/rwaldron/idiomatic.js/#whitespace

We've configured Webstorm to insert spaces within the parentheses of a method call. It seems to apply this coding style to annotations as well.

**Comment by cebor** [comment]
Ok, convinced. Thanks :+1:

**Pull request merged**
